/**
 * app-azure-pr-manager-api
 * App Azure Pool Requests Manager API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: masalinas.gancedo@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PingResponse { 
    greeting?: string;
    date?: string;
    url?: string;
    headers?: { [key: string]: object; };
}

