/**
 * app-azure-pr-manager-api
 * App Azure Pool Requests Manager API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: masalinas.gancedo@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: PoolRequestWithRelations, schemaOptions: { includeRelations: true })
 */
export interface PoolRequestWithRelations { 
  [key: string]: object | any;


    title: string;
    description: string;
    createdBy: string;
    closedDate: string;
    reviewers: Array<string>;
    sourceRefName: string;
    targetRefName: string;
    status: string;
}

